title: Yuanhong Wang
position: Ph.D. Student
affiliation: Beihang University
email: lucienwang [at] buaa [dot] edu [dot] cn
keywords: lucien homepage
google_scholar: https://scholar.google.com/citations?user=08i0uJcAAAAJ&hl=en
github_link: https://github.com/lucienwang1009
linkedin: https://www.linkedin.com/in/yuanhong-wang-61859a108/
avatar: ./assets/img/avatar.png
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
